definitions:
  requests.AuthRequest:
    properties:
      nonce:
        type: string
      signature:
        type: string
      timestamp:
        type: string
    required:
    - nonce
    - signature
    - timestamp
    type: object
  responses.APIResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
  responses.AuthResponse:
    properties:
      access_token:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth:
    post:
      consumes:
      - application/json
      description: Validates AppID header and HMAC signature, then returns a JWT access
        token.
      parameters:
      - description: Client system AppID
        in: header
        name: AppID
        required: true
        type: string
      - description: Authentication request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responses.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/responses.AuthResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responses.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.APIResponse'
      summary: Generate authentication token
      tags:
      - auth
swagger: "2.0"
