apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbe-deployment
spec:
  replicas: 2  # Adjust the number of replicas if needed
  selector:
    matchLabels:
      app: lbe
  template:
    metadata:
      labels:
        app: lbe
    spec:
      containers:
      - name: lbe
        image: rlpmiddleware.azurecr.io/lbe:latest
        ports:
        - containerPort: 18080  # Change this if your app listens on a different port
