apiVersion: v1
kind: Service
metadata:
  name: lbe-service
spec:
  type: LoadBalancer
  selector:
    app: lbe
  ports:
  - protocol: TCP
    port: 80         # External access port; can be adjusted as needed
    targetPort: 18080 # Must match the containerPort in your Deployment
