apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      initContainers:
      - name: fix-tmp-permissions
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - mkdir -p /tmp && chmod 777 /tmp
        securityContext:
          runAsUser: 0
          runAsGroup: 0

      - name: create-system-dir
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - mkdir -p /var/opt/mssql/.system && chmod 777 /var/opt/mssql/.system
        securityContext:
          runAsUser: 0
          runAsGroup: 0

      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "Your@StrongP@ssw0rd"   # Must follow SQL Server password requirements.
          - name: MSSQL_SYSTEM_PATH
            value: "/var/opt/mssql/.system"
        ports:
          - containerPort: 1433
        volumeMounts:
          - name: sqlserver-storage
            mountPath: /var/opt/mssql
        # Diagnostic change: set to run as root temporarily
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: sqlserver-storage
        persistentVolumeClaim:
          claimName: sqlserver-pvc
