
database:
  type: mssql # mssql
  host: 4.145.179.35   # DESKTOP-QMALRMM
  instance:   # SQLEXPRESS
  port: 1433 # 1433
  user: sa # sa
  password: my-secret-pw # Your@StrongP@ssw0rd
  dbname: lbe
  sslmode: disable
  TimeZone: Asia/Shanghai

redis:
  host: localhost
  port: 6379
  password: 123456
  db: 1

jwt:
  jwtSecret: RLP-Version1

log:
  path: /app123/lbe-api

cmd:
  port: 9501
  host: localhost

http:
  port: 18080

api:
  memberservice:
    host : http://localhost:18081 
    appid : App123
    secret: mySuperSecretKey

allStart: 1
proxyEnable : true
 

