
database:
  type: mysql
  host: localhost
  port: 3306
  user: root
  password: my-secret-pw
  dbname: mbc_api_main
  sslmode: disable
  TimeZone: Asia/Shanghai

redis:
  host: localhost
  port: 6379
  password: 123456
  db: 1

jwt:
  jwtSecret: RLP-Version1

log:
  path: /Users/eric_/oneDrive/Desktop/bot

cmd:
  port: 9501
  host: localhost

http:
  port: 18080

allStart: 1
proxyEnable : true


IDP:
  Description: RWS-IDP
  Expires: 10/5/2025
  Value: sAF8Q~kIo5suQ7qvRynlM6EqrAck3.3LPtPTyaeJ
  SecretID: 91c36643-f577-4b5d-bd44-f3386b3e9c87

