
database:
  type: mssql
  host: DESKTOP-QMALRMM
  instance:   SQLEXPRESS # SQLEXPRESS
  port: 1433
  user: sa
  password: 2good2btrue
  dbname: lbe
  sslmode: disable
  TimeZone: Asia/Shanghai

redis:
  host: localhost
  port: 6379
  password: 123456
  db: 1

jwt:
  jwtSecret: RLP-Version1

log:
  path: /app123/lbe-api

cmd:
  port: 9501
  host: localhost

http:
  port: 18080

api:
  memberservice:
    host : http://localhost:18081 
    appid : App123
    secret: mySuperSecretKey

allStart: 1
proxyEnable : true
 
smtp:
  host: smtp.gmail.com
  port: 587
  user: rws.developer.user@gmail.com
  password: xezy owzk xrdu kjhe # Welc0me123$!
  from: rws.developer.user@gmail.com
