
database:
  type: mysql
  host: localhost
  port: 3306
  user: root
  password: my-secret-pw
  dbname: mbc_api_main
  sslmode: disable
  TimeZone: Asia/Shanghai

redis:
  host: localhost
  port: 6379
  password: 123456
  db: 1

jwt:
  jwtSecret: RLP-Version1

log:
  path: /Users/eric_/oneDrive/Desktop/bot

cmd:
  port: 9501
  host: localhost

http:
  port: 18080

allStart: 1
proxyEnable : true
 

