
database:
  type: mssql
  host: DESKTOP-QMALRMM
  instance:   SQLEXPRESS # SQLEXPRESS
  port: 1433
  user: sa
  password: 2good2btrue
  dbname: lbe
  sslmode: disable
  TimeZone: Asia/Shanghai

redis:
  host: localhost
  port: 6379
  password: 123456
  db: 1

jwt:
  jwtSecret: RLP-Version1

log:
  path: /app123/lbe-api

cmd:
  port: 9501
  host: localhost

http:
  port: 18080

api:
  memberservice:
    host : http://localhost:18081 
    appid : App123
    secret: mySuperSecretKey

  rlp:
    host : https://b4eb309d-db93-4378-a3ac-fee2470deb4a.mock.pstmn.io
    apikey : App123 
  cms:
    host : https://3d104014-8ed4-4199-9c6e-84af7f38ae27.mock.pstmn.io
    apikey : App123 
    SystemID: 1234
  eeid:
    host : https://graph.microsoft.com
    authhost : https://login.microsoftonline.com
    tenantid : 854d144f-186e-4849-9dbd-439d971c9984
    clientid : 90b382ed-6609-417f-8213-3f06b442f83c 
    clientsecret: vtf8Q~EPh2Fq4EBh0WSQsRPfxEuVxdcUQ8IDNdgG
    userIdLinkExtensionKey: exth7tu5cmc_LBE
    
allStart: 1
proxyEnable : true
 
smtp:
  host: smtp.gmail.com
  port: 587
  user: rws.developer.user@gmail.com
  password: xezy owzk xrdu kjhe # Welc0me123$!
  from: rws.developer.user@gmail.com
  
application:
  rlpNumberingFormat:
    maxAttempts: 5
    rlpNoDefault: "70000000001"