
database:
  type: mysql
  host: mysql-service
  port: 3306
  user: root
  password: my-secret-pw
  dbname: mbc_api_main
  sslmode: disable
  TimeZone: Asia/Shanghai

redis:
  host: redis
  port: 6379
  password: 123456
  db: 1

jwt:
  jwtSecret: RLP-Version1

log:
  path: /app123/lbe-api

cmd:
  port: 9501
  host: localhost

http:
  port: 18080

allStart: 1
proxyEnable : true
 

