
database:
  type: mysql
  host: mysql-service
  port: 3306
  user: root
  password: my-secret-pw
  dbname: mbc_api_main
  sslmode: disable
  TimeZone: Asia/Shanghai

redis:
  host: redis
  port: 6379
  password: 123456
  db: 1

jwt:
  jwtSecret: RLP-Version1

log:
  path: /app123/rlp-middleware-api

cmd:
  port: 9501
  host: localhost

http:
  port: 18080

allStart: 1
proxyEnable : true

aveConf: 
  avekey: 0xd17e6bd50b29665d0260318165778d0fb60f4de9c83a8332b559841a43c2e6194709923acdeaf036d3aad75203647730f50e2bd80c3f807657934d8c5cf5a36c1c
  aveauth: 62c44255b93cb149574f17da7066ac8d1709878000233074022
  tpl: 120
dex: 
  - name: jup
    chain: SOLANA
    pay: 5000000
    slippage: 300
    increase: 5
    timeout: 90
    vstoken: So11111111111111111111111111111111111111112
    wallet:
      pk: 9KdY9iVCBRtVPCs1txN35fcsZRj1CHnjwWdPqQaZcewScnKXEUs84eH7MrCP4DuVRWTKg448gP7cz97pL735K1P
    targetTokens: 
      - name: BOME
        ca: ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82
        initprice: 0.01
      - name: Slerf
        ca: 7BgBvyjrZX1YKz4oh9mjb8ZScatkkwb8DzFx7LoiVkM3
        initprice: 0.07