package codes

const (
	CODE_SUCCESS              = 0
	CODE_ERR_METHOD_UNSUPPORT = 1
	CODE_ERR_REQFORMAT        = 2
	CODE_ERR_APPID_INVALID    = 3
	CODE_ERR_SIGMETHOD_UNSUPP = 4
	CODE_ERR_AUTHTOKEN_FAIL   = 5
	CODE_ERR_REQ_EXPIRED      = 6
	CODE_ERR_EXIST_OBJ        = 7
	CODE_ERR_BAD_PARAMS       = 8
	CODE_ERR_OBJ_NOT_FOUND    = 9
	CODE_ERR_SIG_COMMON       = 10
	CODE_ERR_CONFIG           = 11
	CODE_ERR_PARA_EMPTY       = 12
	CODE_ERR_TX               = 13
	CODE_ERR_PRIVATEKEY       = 14
	CODE_ERR_SECURITY         = 15
	CODE_ERR_REMOTE           = 16
	CODE_ERR_REPEAT           = 17

	CODE_ERR_OKX = 18

	CODE_ERR_PROCESSING = 800
	CODE_ERR_UNKNOWN    = 900

	CODE_ERR_LAN           = 901
	CODE_ERR_CHAR_BASPARAM = 100
	CODE_ERR_CHAR_UNKNOWN  = 101
	CODE_ERR_CHAR_NOTFOUND = 102
	CODE_ERR_CHAR_ROLE_CAT = 103
	CODE_ERR_CHAR_PARAM    = 104
	CODE_ERR_CHARBACK_MAX  = 105
	CODE_ERR_CHAR_EXIST    = 106

	CODE_ERR_GPT_COMPLETE   = 201
	CODE_ERR_GPT_STREAM     = 202
	CODE_ERR_GPT_STREAM_EOF = 203
)
